# Generated by Django 5.0.6 on 2024-05-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('cargo', models.ManyToManyField(to='cargo.cargo')),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
