# Generated by Django 5.0.6 on 2024-05-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='cargo',
        ),
    ]
