# Generated by Django 5.0.6 on 2024-05-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('doc_identidad', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='photos/profile')),
                ('estado', models.BooleanField(default=True)),
                ('f_inicio', models.DateField(blank=True, null=True)),
                ('f_cese', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area.area')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
    ]
