# Generated by Django 5.0.6 on 2024-05-20 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('doc_identidad', models.IntegerField()),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='photos/profile')),
                ('is_active', models.BooleanField(default=True)),
                ('f_ingreso', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
