# Generated by Django 5.0.6 on 2024-05-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
