# Generated by Django 5.0.6 on 2024-05-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo'),
        ),
    ]
