# Generated by Django 5.0.6 on 2024-05-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleados_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
