# Generated by Django 5.0.6 on 2024-05-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleados_options_cargo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='doc_identidad',
            field=models.CharField(max_length=12),
        ),
    ]
