# Generated by Django 5.0.6 on 2024-05-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleados_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
